[api]
url='https://www.themuse.com/api/public/jobs?page=50'

[sql]
filename='Top10CustomerIDBySales.sql'

[aws]
bucketname='jackie-aws-projects'
foldername='muse-job/'

[run]
py_script="muse-job-api.py"
filename ='page50_sample_job_descriptions_test.csv'
