[api]
url='https://virtserver.swaggerhub.com/wcd_de_lab/top10/1.0.0/add'

[sql]
filename='Top10CustomerIDBySales.sql'
hostname='aws-mysql.colmzgu114nj.us-east-1.rds.amazonaws.com'
port='3306'
database='superstore'

[s3]
bucketname='jackie-aws-projects'
foldername='customer-superstore/'
filename='top10customers.json'

[run]
py_script="muse-job-api.py"
filename ='page50_sample_job_descriptions_test.csv'
